services:
  postgres:
    image: postgres:18
    container_name: marine-postgres
    environment:
      POSTGRES_DB: marine-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 12345
      TZ: UTC
      PGTZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - marine_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./marine-backend
    container_name: marine-backend
    depends_on:
      - postgres
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/marine-db?options=-c%20TimeZone=UTC
      DB_USERNAME: admin
      DB_PASSWORD: 12345
      JPA_DDL_AUTO: update
      JWT_SECRET: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      JWT_EXPIRATION_MS: 86400000
      CORS_ALLOWED_ORIGINS: http://localhost:5173,http://localhost:3000,http://127.0.0.1:5173,http://127.0.0.1:3000
      SERVER_PORT: 8080
      TZ: UTC
    ports:
      - "8080:8080"

volumes:
  marine_postgres_data:
